#!/bin/bash
action=$1
title=""
name="project"
links=""
author="Arden Rasmussen"
version="1.0"
copy="Arden Rasmussen"
docs=true
ShowHelp () 
{
  printf "Help Page\n"
  printf "==========\n"
  printf ""
  exit 1
}

CreateProject () 
{
  printf "Creating Project $name\n"
  mkdir "$name"
  cp ~/bin/.project_files/* ./$name/ -r 
  subdir=$name"_files"
  SetVars
}

SetVars ()
{
  if [ "$title" == "" ]; then
    title="${name^}"
  fi
  underline=$(printf '%*s\n' $((${#title} + 14)) | tr ' ' =)
  cd $name
  find -type f -exec sed -i "s/project_title/$title/g" {} +
  find -type f -exec sed -i "s/project_name/$name/g" {} +
  find -type f -exec sed -i "s/project_link/$links/g" {} +
  find -type f -exec sed -i "s/project_author/$author/g" {} +
  find -type f -exec sed -i "s/project_version/$version/g" {} +
  find -type f -exec sed -i "s/project_copy/$copy/g" {} +
  find -type f -exec sed -i "s/title_underline/$underline/g" {} +
}

GetOpts ()
{
  for (( i=2; i<=$#; i++)); do
    j=$((i+1))
    GetOpt ${!i} ${!j}
  done
}

GetOpt ()
{
  opt=$1
  arg=$2
  if [ "$opt" == "-n" ] || [ "$opt" == "-name" ]; then
    name=$arg
  elif [ "$opt" == "-l" ] || [ "$opt" == "-link" ]; then
    links=$arg
  fi
}

if [ "$action" == "new" ]; then
  GetOpts "$@"
  CreateProject
elif [ "$action" == "--help" ]; then
  ShowHelp
else
  ShowHelp
fi
